name: package
on:
  push:
    branches: [main]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 23.8.x
          registry-url: 'https://registry.npmjs.org/'
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Install dependencies
        run: npm ci
      - name: Package
        run: vsce package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Extension vsix
          path: vscode-flowr-*.vsix
